version: '3.8'

services:
  financier-bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - default
      - nouvier-web

networks:
  nouvier-web:
    external: true
    name: nouvier-web_default
